services:
  rabbitmq:
    image: "rabbitmq:3.13-management-alpine"
    container_name: learn-rmq-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=user'

volumes:
  rabbitmq_data:

